version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ../:/var/www
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        networks:
            - app-network
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        entrypoint: ""
        command: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email your@email.com --agree-tos --no-eff-email -d 45.153.191.182 --dry-run && certbot renew"
        depends_on:
            - nginx
        networks:
            - app-network


    php:
        build:
            context: .
            dockerfile: php/Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - ../:/var/www
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lantaservice
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        command: [
            "mysqld",
            "--character-set-server=utf8",
            "--collation-server=utf8_unicode_ci",
            "--innodb-ft-min-token-size=1"
        ]
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: pma
        ports:
            - "8876:80"
        environment:
            PMA_HOST: "mysql"
            UPLOAD_MAX_FILESIZE: 512M
            POST_MAX_SIZE: 512M
            MAX_EXECUTION_TIME: 3000
        depends_on:
            - mysql
        networks:
            - app-network

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network


volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge
